[package]
name = "nydus-rs"
version = "2.1.0-alpha2"
description = "Nydus Image Service"
authors = ["The Nydus Developers"]
license = "Apache-2.0 OR BSD-3-Clause"
homepage = "https://nydus.dev/"
repository = "https://github.com/dragonflyoss/image-service"
edition = "2018"

[profile.release]
panic = "abort"

[[bin]]
name = "nydusd"
path = "src/bin/nydusd/main.rs"

[lib]
name = "nydus"
path = "src/lib.rs"

[dependencies]
rlimit = "0.8.3"
log = "0.4.8"
libc = "0.2"
vmm-sys-util = "0.10.0"
clap = "2.33"
flexi_logger = { version = "0.17" }
# pin regex to fix RUSTSEC-2022-0013
regex = "1.5.5"
serde = { version = "1.0.110", features = ["serde_derive", "rc"] }
serde_json = "1.0.51"
serde_with = { version = "1.6.0", features = ["macros"] }
sha2 = "0.10.2"
lazy_static = "1.4.0"
xattr = "0.2.2"
nix = "0.24.0"
anyhow = "1.0.35"
base64 = "0.13.0"
rust-fsm = "0.6.0"
vm-memory = { version = "0.8.0", features = ["backend-mmap"], optional = true }
chrono = "0.4.19"
openssl = { version = "0.10.40", features = ["vendored"] }
# pin openssl-src to bring in fix for https://rustsec.org/advisories/RUSTSEC-2022-0032
openssl-src = { version = "111.22" }
hyperlocal = "0.8.0"
tokio = { version = "1.18.2", features = ["macros"] }
hyper = "0.14.11"
# pin rand_core to bring in fix for https://rustsec.org/advisories/RUSTSEC-2021-0023
rand_core = "0.6.2"
tar = "0.4.38"
mio = { version = "0.8", features = ["os-poll", "os-ext"] }

fuse-backend-rs = { version = "0.9.5" }
vhost = { version = "0.4.0", features = ["vhost-user-slave"], optional = true }
vhost-user-backend = { version = "0.5.1", optional = true }
virtio-bindings = { version = "0.1", features = ["virtio-v5_0_0"], optional = true }
virtio-queue = { version = "0.4.0", optional = true }

nydus-api = { version = "0.1.0", path = "api" }
nydus-app = { version = "0.3.0", path = "app" }
nydus-error = { version = "0.2.1", path = "error" }
nydus-rafs = { version = "0.1.0", path = "rafs", features = ["backend-registry", "backend-oss"] }
nydus-storage = { version = "0.5.0", path = "storage" }
nydus-utils = { version = "0.3.0", path = "utils" }
nydus-blobfs = { version = "0.1.0", path = "blobfs", features = ["virtiofs"], optional = true }

[dev-dependencies]
sendfd = "0.3.3"
env_logger = "0.8.2"
rand = "0.8.5"

[features]
fusedev = ["fuse-backend-rs/fusedev"]
virtiofs = ["fuse-backend-rs/vhost-user-fs", "vm-memory", "vhost", "vhost-user-backend", "virtio-queue", "virtio-bindings"]

[workspace]
members = ["api", "app", "error", "rafs", "storage", "utils", "blobfs"]
