[package]
name = "nydus-rs"
# will be overridden by real git tag during cargo build
version = "0.0.0-git"
description = "Nydus Image Service"
authors = ["The Nydus Developers"]
license = "Apache-2.0 OR BSD-3-Clause"
homepage = "https://nydus.dev/"
repository = "https://github.com/dragonflyoss/image-service"
edition = "2018"
resolver = "2"

[profile.release]
panic = "abort"

[[bin]]
name = "nydusctl"
path = "src/bin/nydusctl/main.rs"

[[bin]]
name = "nydusd"
path = "src/bin/nydusd/main.rs"

[[bin]]
name = "nydus-image"
path = "src/bin/nydus-image/main.rs"

[lib]
name = "nydus"
path = "src/lib.rs"

[dependencies]
anyhow = "1"
base64 = "0.13.0"
clap = { version = "4.0.18", features = ["derive", "cargo"] }
fuse-backend-rs = "0.10.1"
hex = "0.4.3"
hyper = "0.14.11"
hyperlocal = "0.8.0"
indexmap = "1"
lazy_static = "1"
libc = "0.2"
log = "0.4.8"
mio = { version = "0.8", features = ["os-poll", "os-ext"] }
nix = "0.24.0"
rlimit = "0.9.0"
rust-fsm = "0.6.0"
serde = { version = "1.0.110", features = ["serde_derive", "rc"] }
serde_json = "1.0.51"
sha2 = "0.10.2"
tar = "0.4.38"
thiserror = "1.0"
time = { version = "0.3.14", features = ["serde-human-readable"] }
tokio = { version = "1.24", features = ["macros"] }
vmm-sys-util = "0.10.0"
xattr = "0.2.3"

# Build static linked openssl library
openssl = { version = "0.10.45", features = ["vendored"] }
# pin openssl-src to bring in fix for https://rustsec.org/advisories/RUSTSEC-2022-0032
#openssl-src = { version = "111.22" }

nydus-api = { version = "0.2.0", path = "api", features = ["handler"] }
nydus-app = { version = "0.3.2", path = "app" }
nydus-error = { version = "0.2.3", path = "error" }
nydus-rafs = { version = "0.2.0", path = "rafs", features = [
    "backend-registry",
    "backend-oss",
    "backend-s3",
    "backend-http-proxy",
    "backend-localdisk",
] }
nydus-storage = { version = "0.6.0", path = "storage" }
nydus-utils = { version = "0.4.0", path = "utils" }

nydus-blobfs = { version = "0.2.0", path = "blobfs", features = ["virtiofs"], optional = true }

vhost = { version = "0.5.0", features = ["vhost-user-slave"], optional = true }
vhost-user-backend = { version = "0.7.0", optional = true }
virtio-bindings = { version = "0.1", features = ["virtio-v5_0_0"], optional = true }
virtio-queue = { version = "0.6.0", optional = true }
vm-memory = { version = "0.9.0", features = ["backend-mmap"], optional = true }

[features]
default = ["fuse-backend-rs/fusedev"]
virtiofs = [
    "fuse-backend-rs/vhost-user-fs",
    "vm-memory",
    "vhost",
    "vhost-user-backend",
    "virtio-queue",
    "virtio-bindings",
]

[workspace]
members = ["api", "app", "blobfs", "clib", "error", "rafs", "storage", "utils"]
