[package]
name = "nydus-rs"
version = "2.0.1"
authors = ["The Nydus Developers"]
edition = "2018"
license = "Apache-2.0 OR BSD-3-Clause"

[profile.release]
panic = "abort"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "nydusd"
path = "src/bin/nydusd/main.rs"

[lib]
name = "nydus"
path = "src/lib.rs"


[dependencies]
rlimit = "0.8.3"
log = "0.4.8"
libc = "0.2"
vmm-sys-util = "0.9.0"
clap = "2.33"
flexi_logger = { version = "0.17" }
# pin regex to fix RUSTSEC-2022-0013
regex = "1.5.5"
serde = { version = "1.0.110", features = ["serde_derive", "rc"] }
serde_json = "1.0.51"
serde_with = { version = "1.6.0", features = ["macros"] }
sha2 = "0.10.2"
lazy_static = "1.4.0"
xattr = "0.2.2"
nix = "0.23.1"
anyhow = "1.0.35"
base64 = "0.13.0"
rust-fsm = "0.6.0"
vm-memory = { version = "0.7.0", features = ["backend-mmap"], optional = true }
chrono = "0.4.19"
openssl = { version = "0.10.38", features = ["vendored"] }
hyperlocal = "0.8.0"
tokio = { version = "1.18.2", features = ["macros"] }
hyper = "0.14.11"
# pin rand_core to bring in fix for RUSTSEC-2021-0023
rand_core = "0.6.2"
tar = "0.4.38"
mio = { version = "0.8", features = ["os-poll", "os-ext"]}

fuse-backend-rs = { version = "0.9.0", optional = true }
vhost = { version = "0.3.0", features = ["vhost-user-slave"], optional = true }
vhost-user-backend = { version = "0.1.0", optional = true }
virtio-bindings = { version = "0.1", features = ["virtio-v5_0_0"], optional = true }
virtio-queue = { version = "0.1.0", optional = true }

nydus-api = { path = "api" }
nydus-app = { path = "app" }
nydus-error = { path = "error" }
nydus-rafs = { version = "0.1.0", path = "rafs", features = ["backend-registry", "backend-oss"] }
nydus-storage = { version = "0.5.0", path = "storage" }
nydus-utils = { version = "0.2.0", path = "utils" }
blobfs = { path = "blobfs", features = ["virtiofs"], optional = true }

[target.'cfg(target_os = "linux")'.dependencies]
event-manager = "0.2.1"

[dev-dependencies]
sendfd = "0.3.3"
vmm-sys-util = "0.9.0"
env_logger = "0.8.2"
rand = "0.8.5"

[features]
fusedev = ["nydus-utils/fusedev", "fuse-backend-rs/fusedev"]
virtiofs = ["fuse-backend-rs/vhost-user-fs", "vm-memory", "vhost", "vhost-user-backend", "virtio-queue", "virtio-bindings"]

[workspace]
members = ["api", "app", "error", "rafs", "storage", "utils", "blobfs"]
