version = 2
root = "/var/lib/containerd"
state = "/run/containerd"
oom_score = 0

[debug]
  level = "debug"

[plugins."io.containerd.grpc.v1.cri".containerd]
  snapshotter = "nydus"
  disable_snapshot_annotations = false
  discard_unpacked_layers = false

[proxy_plugins]
  [proxy_plugins.nydus]
      type = "snapshot"
      address = "/run/containerd-nydus/containerd-nydus-grpc.sock"
